### PR TITLE
adjust value of allowed max gas for a call sc

### PR DESCRIPTION
**Pull request by Thykof**

### CODE REVIEW

**Comment by Thykof** [comment]
node says `which is above the maximum allowed 4294967295`

**Comment by Thykof** [comment]
The node error message is wrong, for a Call SC operation the maximun max_gas value is 2^32-1-800000=4_294_167_295

**Comment by Ben-Rey** [comment]
Sorry just saw your pr. I fixed it here https://github.com/massalabs/massa-web3/pull/507

**Comment by Ben-Rey** [comment]
Sorry just saw your pr. I fixed it here https://github.com/massalabs/massa-web3/pull/507

**Pull request closed without merging**
